# Generated by Django 5.2.7 on 2025-10-09 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('endpoint', models.URLField(help_text='HTTP URL вида http://host:port/metrics')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.IntegerField()),
                ('mem_percent', models.FloatField()),
                ('disk_percent', models.FloatField()),
                ('uptime', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='monitoring.machine')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['machine', 'received_at'], name='monitoring__machine_77b012_idx')],
            },
        ),
    ]
