# Generated by Django 5.2.7 on 2025-10-10 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CPU_HIGH', 'CPU > 85%'), ('MEM_HIGH', 'MEM > 90% (30m)'), ('DISK_HIGH', 'DISK > 95% (2h)')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='monitoring.machine')),
            ],
            options={
                'indexes': [models.Index(fields=['machine', 'type', 'is_active'], name='monitoring__machine_92e7b6_idx'), models.Index(fields=['started_at'], name='monitoring__started_716c59_idx')],
            },
        ),
    ]
